-- MySQL Script generated by MySQL Workbench
-- lun 11 nov 2019 20:36:27 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb

-- -----------------------------------------------------
-- Table `tipodocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipodocumento` (
  `tipodoc_id` INT(11) NOT NULL,
  `tipodoc_nombre` VARCHAR(45) NOT NULL,
  `tipodoc_descripcion` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`tipodoc_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `usu_documento` VARCHAR(45) NOT NULL,
  `tipodoc_id` INT(11) NOT NULL,
  `usu_nombres` VARCHAR(45) NOT NULL,
  `usu_apellidos` VARCHAR(45) NOT NULL,
  `usu_fechanac` DATE NULL DEFAULT NULL,
  `usu_correo` VARCHAR(80) NOT NULL,
  `usu_ubicacion` VARCHAR(100) NOT NULL DEFAULT 'Cúcuta',
  `usu_contrasena` VARCHAR(255) NOT NULL,
  `usu_rol_id` INT(11) NOT NULL,
  PRIMARY KEY (`usu_documento`),
  UNIQUE INDEX `usu_correo_UNIQUE` (`usu_correo` ASC),
  UNIQUE INDEX `usu_documento_UNIQUE` (`usu_documento` ASC),
  INDEX `fk_usutipodoc_idx` (`tipodoc_id` ASC),
  CONSTRAINT `fk_usutipodoc`
    FOREIGN KEY (`tipodoc_id`)
    REFERENCES `tipodocumento` (`tipodoc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `asesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asesor` (
  `idasesor` INT(11) NOT NULL,
  `usuario_usu_documento` VARCHAR(45) NOT NULL,
  `usas_experiencia` FLOAT(8,2) NOT NULL,
  `usas_biografia` VARCHAR(500) NOT NULL DEFAULT 'Soy un excelente docente dedicado a compartir mi conocimiento',
  `usas_fechacreacion` DATE NOT NULL,
  PRIMARY KEY (`idasesor`, `usuario_usu_documento`),
  UNIQUE INDEX `idasesor_UNIQUE` (`idasesor` ASC),
  CONSTRAINT `fk_usu_documento`
    FOREIGN KEY (`usuario_usu_documento`)
    REFERENCES `usuario` (`usu_documento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asignatura` (
  `idasignatura` INT(11) NOT NULL,
  `descripcion` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`idasignatura`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aula` (
  `aula_id` INT(11) NOT NULL,
  `aula_numero` VARCHAR(45) NOT NULL,
  `blo_id` INT(11) NOT NULL,
  PRIMARY KEY (`aula_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudiante` (
  `idestudiante` INT(11) NOT NULL,
  `usuario_usu_documento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestudiante`),
  UNIQUE INDEX `idestudiante_UNIQUE` (`idestudiante` ASC),
  INDEX `fk_estudiante_usuario1_idx` (`usuario_usu_documento` ASC),
  CONSTRAINT `fk_estudiante_usuario1`
    FOREIGN KEY (`usuario_usu_documento`)
    REFERENCES `usuario` (`usu_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `asesoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asesoria` (
  `ase_id` INT(11) NOT NULL,
  `ase_fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `aula_id` INT(11) NOT NULL,
  `cali_id` INT(11) NOT NULL,
  `idestudiante` INT(11) NOT NULL,
  `idasesor` INT(11) NOT NULL,
  `asignatura_idasignatura` INT(11) NOT NULL,
  `calificacion` INT(11) NULL DEFAULT NULL,
  `observacion` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`ase_id`, `ase_fecha`),
  INDEX `fk_asesoria_aula1_idx` (`aula_id` ASC),
  INDEX `fk_asesoria_estudiante1_idx` (`idestudiante` ASC),
  INDEX `fk_asesoria_asesor1_idx` (`idasesor` ASC),
  INDEX `fk_asesoria_asignatura1_idx` (`asignatura_idasignatura` ASC),
  CONSTRAINT `fk_asesoria_asesor1`
    FOREIGN KEY (`idasesor`)
    REFERENCES `asesor` (`idasesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asesoria_asignatura1`
    FOREIGN KEY (`asignatura_idasignatura`)
    REFERENCES `asignatura` (`idasignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asesoria_aula1`
    FOREIGN KEY (`aula_id`)
    REFERENCES `aula` (`aula_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asesoria_estudiante1`
    FOREIGN KEY (`idestudiante`)
    REFERENCES `estudiante` (`idestudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `asesor_asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asesor_asignatura` (
  `idasesor_asignatura` INT(11) NOT NULL,
  `asesor_idasesor` INT(11) NOT NULL,
  `asignatura_idasignatura` INT(11) NOT NULL,
  PRIMARY KEY (`idasesor_asignatura`),
  UNIQUE INDEX `idasesor_asignatura_UNIQUE` (`idasesor_asignatura` ASC),
  INDEX `fk_asesor_asignatura_asesor1_idx` (`asesor_idasesor` ASC),
  INDEX `fk_asesor_asignatura_asignatura1_idx` (`asignatura_idasignatura` ASC),
  CONSTRAINT `fk_asesor_asignatura_asesor1`
    FOREIGN KEY (`asesor_idasesor`)
    REFERENCES `asesor` (`idasesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asesor_asignatura_asignatura1`
    FOREIGN KEY (`asignatura_idasignatura`)
    REFERENCES `asignatura` (`idasignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dia` (
  `iddia` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`iddia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hora` (
  `idhora` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idhora`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `disponibilidad_asesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `disponibilidad_asesor` (
  `id_disponibilidad` INT(11) NOT NULL,
  `dia` INT(11) NOT NULL,
  `hora` INT(11) NOT NULL,
  `asesor` INT(11) NOT NULL,
  PRIMARY KEY (`id_disponibilidad`),
  INDEX `fk_disponibilidad_asesor_dia1_idx` (`dia` ASC),
  INDEX `fk_disponibilidad_asesor_hora1_idx` (`hora` ASC),
  INDEX `fk_disponibilidad_asesor_asesor1_idx` (`asesor` ASC),
  CONSTRAINT `fk_disponibilidad_asesor_asesor1`
    FOREIGN KEY (`asesor`)
    REFERENCES `asesor` (`idasesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disponibilidad_asesor_dia1`
    FOREIGN KEY (`dia`)
    REFERENCES `dia` (`iddia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disponibilidad_asesor_hora1`
    FOREIGN KEY (`hora`)
    REFERENCES `hora` (`idhora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telefono` (
  `tele_id` INT(11) NOT NULL,
  `tele_numero` VARCHAR(45) NOT NULL,
  `tele_tipo` VARCHAR(45) NOT NULL,
  `usuario_usu_documento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tele_id`),
  INDEX `fk_telefono_usuario1_idx` (`usuario_usu_documento` ASC),
  CONSTRAINT `fk_telefono_usuario1`
    FOREIGN KEY (`usuario_usu_documento`)
    REFERENCES `usuario` (`usu_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `recomendados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recomendados` (
  `estudiante_idestudiante` INT(11) NOT NULL,
  `asesor_idasesor` INT(11) NOT NULL,
  PRIMARY KEY (`estudiante_idestudiante`, `asesor_idasesor`),
  INDEX `fk_estudiante_has_asesor_asesor1_idx` (`asesor_idasesor` ASC),
  INDEX `fk_estudiante_has_asesor_estudiante1_idx` (`estudiante_idestudiante` ASC),
  CONSTRAINT `fk_estudiante_has_asesor_estudiante1`
    FOREIGN KEY (`estudiante_idestudiante`)
    REFERENCES `estudiante` (`idestudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_has_asesor_asesor1`
    FOREIGN KEY (`asesor_idasesor`)
    REFERENCES `asesor` (`idasesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
